version: '3.8'
services:
  postgresql_server:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres" 
      POSTGRES_DB: "perncrud"
    ports:
      - "5432:5432"
    volumes: 
      # copy the sql script to create tables
      - ./data/pgsql:/var/lib/postgresql/data
      - ./server/db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  backend:
    container_name: backend
    build:
      context: server
      dockerfile: Dockerfile # Dockerfile in server folder
    ports:
      - 5000:5000
    depends_on:
      - postgresql_server
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: client
      dockerfile: Dockerfile # Dockerfile in client folder
    ports:
      - 3000:3000
    restart: always